name: Trivy Scan

on:
  push:
    branches:
      - Dev
    paths:
      - '.github/workflows/Fail_trivy.yml'
      - 'Dockerfile'
      - '**/*.java'
      - 'build.gradle'
  pull_request:
    branches:
      - Dev
    paths:
      - '.github/workflows/trivy.yml'
      - 'Dockerfile'
      - '**/*.java'
      - 'build.gradle'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout source code
        uses: actions/checkout@v4

      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      
     # Build Project
      - name: Build Project
        run: ./gradlew clean build

   # -----------------------------
    # Verify Build Output
    # -----------------------------
      - name: Verify JAR
        run: ls -lh build/libs/

    # -----------------------------
    # Build Docker Image
    # -----------------------------
      - name: Build Docker Image
        run: docker build -t sastpoc-app:latest .

    # -----------------------------
    # Trivy Image Scan
    # -----------------------------
      - name: Run Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          scan-type: 'image'
          image-ref: 'sastpoc-app:latest'
          format: 'json'
          output: 'trivy-image-report.json'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'
          

    # -----------------------------
    # Upload Trivy Report
    # -----------------------------
      - name: Upload Trivy Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-image-report
          path: trivy-image-report.json


      - name: Fail if HIGH or CRITICAL vulnerabilities found
        run: |
         if grep -qE '"Severity": ?"(HIGH|CRITICAL)"' trivy-image-report.json; then
         echo "❌ HIGH or CRITICAL vulnerabilities found!"
         exit 1
         else
         echo "✅ No HIGH or CRITICAL vulnerabilities"
         fi

